"""empty message

Revision ID: 0484f495048d
Revises: 627ad2586c51
Create Date: 2026-02-19 15:17:50.495725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0484f495048d'
down_revision = '627ad2586c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('visited',
               existing_type=sa.BOOLEAN(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_po_visited'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_visited'), ['visited'], unique=False)
        batch_op.alter_column('visited',
               existing_type=sa.DateTime(),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('visited_date')

    # ### end Alembic commands ###
