"""move address to street

Revision ID: 2dbb2fcd5b44
Revises: 2368b8aacb36
Create Date: 2026-02-04 01:02:47.903387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbb2fcd5b44'
down_revision = '2368b8aacb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_po')
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.alter_column('address', new_column_name='street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.alter_column('street', new_column_name='address')
    # ### end Alembic commands ###
