"""empty message

Revision ID: 5264d57913d0
Revises: 
Create Date: 2026-02-04 20:08:21.979236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5264d57913d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po',
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('street', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('visited', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.String(length=10), nullable=True),
    sa.Column('longitude', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('zip')
    )
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_city'), ['city'], unique=True)
        batch_op.create_index(batch_op.f('ix_po_visited'), ['visited'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_visited'))
        batch_op.drop_index(batch_op.f('ix_po_city'))

    op.drop_table('po')
    # ### end Alembic commands ###
