"""fresh start

Revision ID: 59be12cbc27b
Revises: 
Create Date: 2026-01-19 18:13:44.983105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59be12cbc27b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po',
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('zip')
    )
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_city'), ['city'], unique=True)
        batch_op.create_index(batch_op.f('ix_po_visited'), ['visited'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_visited'))
        batch_op.drop_index(batch_op.f('ix_po_city'))

    op.drop_table('po')
    # ### end Alembic commands ###
