"""empty message

Revision ID: b69d281fbc4e
Revises: 0484f495048d
Create Date: 2026-02-19 20:01:05.528038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69d281fbc4e'
down_revision = '0484f495048d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.alter_column('visited',
               existing_type=sa.DATETIME(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po', schema=None) as batch_op:
        batch_op.alter_column('visited',
               existing_type=sa.Boolean(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
