City                 | Zip    | Distance (mi)   | Status
------------------------------------------------------------
#ALEXANDER            | 28701  | 7809.21         | ❌  FLAG
#CUMBERLAND           | 28331  | 87.72           | ❌  FLAG
#EAGLE SPRINGS        | 27242  | 50.02           | ❌  FLAG
#EVERGREEN            | 28438  | 93.39           | ❌  FLAG
#FAIRFIELD            | 27826  | 133.94          | ❌  FLAG
#GOLD HILL            | 28071  | 76.80           | ❌  FLAG
#GRASSY CREEK         | 28631  | 58.63           | ❌  FLAG
#HARRIS               | 28074  | 200.72          | ❌  FLAG
#HENRIETTA            | 28076  | 239.93          | ❌  FLAG
#LAKEVIEW             | 28350  | 68.02           | ❌  FLAG
#MILLERS CREEK        | 28651  | 148.38          | ❌  FLAG
#NEBO                 | 28761  | 78.86           | ❌  FLAG
#PENDLETON            | 27862  | 175.62          | ❌  FLAG
#PLEASANT HILL        | 27866  | 238.74          | ❌  FLAG
#PROVIDENCE           | 27315  | 44.15           | ❌  FLAG
#RIDGEWAY             | 27570  | 49.24           | ❌  FLAG
#SANDY RIDGE          | 27046  | 242.35          | ❌  FLAG
#SHILOH               | 27974  | 368.25          | ❌  FLAG
#SOUTHMONT            | 27351  | 36.88           | ❌  FLAG
#TIMBERLAKE           | 27583  | 91.42           | ❌  FLAG
#UNION GROVE          | 28689  | 243.38          | ❌  FLAG
#WEST END             | 27376  | 51.92           | ❌  FLAG
#WESTFIELD            | 27053  | 98.59           | ❌  FLAG
#WHITE OAK            | 28399  | 72.09           | ❌  FLAG
------------------------------------------------------------
